version: '3.8'

services:
  price_predictor:
    build: .
    container_name: price_predictor_app
    ports:
      - "8000:8000"
      - "9001:9001"  # Supervisor web interface
    volumes:
      - ./media:/app/media
      - ./mystaticfiles:/app/mystaticfiles
      - ./db.sqlite3:/app/db.sqlite3
    env_file:
      - .env
    environment:
      # Override specific values if needed
      - CELERY_BROKER_URL=redis://127.0.0.1:6379/0
      - CELERY_RESULT_BACKEND=redis://127.0.0.1:6379/0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
